# Generated by Django 4.1 on 2022-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlocation',
            name='shop_image',
            field=models.ImageField(blank=True, help_text='Upload Shop Name', null=True, upload_to='images/shop_image/'),
        ),
    ]
