# Generated by Django 4.1 on 2022-11-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_registerlocation_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('elocation', models.CharField(max_length=100)),
                ('ereview', models.FloatField()),
                ('ediscount', models.CharField(max_length=50)),
                ('ephone', models.IntegerField(default=0)),
                ('eaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
